### ISSUE TITLE
No slounik.org articles on Nexus

### ISSUE THREAD

**Issue by anibyl** [anibyl/slounik#3]
No slounik.org articles on Samsung Galaxy Nexus. Android 4.3. Cyanogenmod 10.2.1
![photo_2018-02-19_19-23-31](https://user-images.githubusercontent.com/790717/36387586-672464d4-15aa-11e8-8d34-8445d040bf29.jpg) 
![photo_2018-02-19_19-23-34](https://user-images.githubusercontent.com/790717/36387589-6afb8f9c-15aa-11e8-8dc9-0f9f4277087a.jpg)

**Comment by Zmicier21** [comment]
No slounik.org articles on Samsung A52. Android 12 
![Screenshot_20220506-235850_Slounik](https://user-images.githubusercontent.com/95053350/167215664-4c933443-ef19-4b3a-b920-8886e63bab7a.jpg)
![Screenshot_20220506-235857_Slounik](https://user-images.githubusercontent.com/95053350/167215676-97323f3a-3401-4c3e-8c7f-40240ce729c7.jpg)
![Screenshot_20220506-235907_Slounik](https://user-images.githubusercontent.com/95053350/167215686-2638184f-bd57-483f-aa5e-cb9602ca3dfa.jpg)
![Screenshot_20220506-235911_Slounik](https://user-images.githubusercontent.com/95053350/167215693-733a4ce6-5c57-48c0-9dd8-52b006d9c2c0.jpg)

**Comment by anibyl** [comment]
Hi, I'm aware of the issue, it seems to be device specific. I will fix it eventually. You could opt out of beta and install an earlier version where slounik.org integration works fine.

**Comment by anibyl** [comment]
I am closing the issue as there's no more activity and I updated slounik.org integration is the previous release.
