### ISSUE TITLE
Афіцыйны правапіс

### ISSUE THREAD

**Issue by antikruk** [anibyl/slounik#4]
Вітаю, у вас атрымаўся вельмі зручны дадатак, але ўсё ж было вельмі пажадана мець інтэрфейс афіцыйным правапісам, альбо рэалізаваць магчымасць выбару паміж афіцыйным і класічным.

**Comment by anibyl** [comment]
1. Гэта немагчыма ў цяперашняй кананічнай рэалізацыі з тэхнічнага боку. Калі, напрыклад, нарвэская мова мае bokmal (nb) і nunorsk (nn) варыянты — у беларускай мовы гэтых варыянтаў няма.

2. Сама праграма выкарыстоўвае толькі 2 словы, адрозныя ў напісаньні (https://github.com/anibyl/slounik/blob/master/main/src/main/res/values-be/strings.xml), адно зь якіх у апісаньні праграмы, другое — у назьве аднаго са слоўнікаў на rv-blr.com. Наўрад ці менавіта яны зачапілі вашу ўвагу. Усе астатнія тэксты бяруцца з уласна слоўнікавых сайтаў — напрыклад, slounik.org. Іх мяняць нельга.

**Comment by antikruk** [comment]
1. Я ўжо бачыў рэалізацыю ў абход ISO. Напрыклад, так зроблена ў Fbreader. Але, калі гэта цяжка, то мо і сэнсу не мае.  
2. Не, я менавіта пра інтэрфейс казаў. Хочацца аднароднасці.  На сайтах жа старыя слоўнікі выкладаюцца. Усё ж падумайце пра прапанову пераходу на афіцыйны правапіс. 
Дзякую за ўвагу
